//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Faculdade
{
    using System;
    using System.Collections.Generic;
    
    public partial class curso
    {
        public decimal id { get; set; }
        public string nome { get; set; }
        public string grau { get; set; }
        public string codigo_MEC { get; set; }
        public string autorização_DOU { get; set; }
        public System.DateTime data_autorizacao_DOU { get; set; }
        public string reconhecimento_DOU { get; set; }
        public System.DateTime data_reconhecimento_DOU { get; set; }
        public string renovacao_DOU { get; set; }
        public System.DateTime data_renovacao_DOU { get; set; }
        public string observação { get; set; }
    }
}
