//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Faculdade
{
    using System;
    using System.Collections.Generic;
    
    public partial class diploma
    {
        public decimal id { get; set; }
        public string nome_aluno { get; set; }
        public string cpf_aluno { get; set; }
        public System.DateTime data_emissao { get; set; }
        public bool validado { get; set; }
        public Nullable<decimal> id_usuario_validacao { get; set; }
        public decimal id_instituicao { get; set; }
    
        public virtual usuario usuario { get; set; }
        public virtual instituicao instituicao { get; set; }
    }
}
